name: Cron

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

  schedule: 
    - cron:  '0 */2 * * *'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12]

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: yarn install, generate
        run: |
          yarn install
          yarn gen-domain-set

      - name: commit, push
        uses: EndBug/add-and-commit@v5
        with:
          add: 'domain-set'
          author_name: mangoclover
          author_email: 48041092+mangoclover@users.noreply.github.com
          message: 'auto update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge CDN Cache
        run: |
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/adaway.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/annoyances-filter.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/base-filter.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/chinese-filter.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/neohosts-full.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/neohosts.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/social-media-filter.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/tracking-protection-filter.txt > /dev/null 2>&1
          curl -L https://cdn.jsdelivr.net/gh/mangoclover/surge-list/domain-set/dns-filter.txt > /dev/null 2>&1
          
